# Generated by Django 4.1.3 on 2023-03-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_remove_product_brand_remove_productoffer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='days_until_shipment',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoffer',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
